version: 2

jobs:
  build:

    docker:
        - image: gcc:5.4.0

    steps:
      - checkout
      - run: apt update
      - run: apt install -y zip
      - run: make release
      - run: make
      - run:
          name: make driver
          command: |
              cd release/sps30-i2c && make && make clean && cd -
